groups:
  - name: cAdvisor

    rules:
      - alert: ContainerKilled
        expr: 'time() - container_last_seen > 60'
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Container killed (instance {{ $labels.instance }})
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerAbsent
        expr: 'absent(container_last_seen)'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Container absent (instance {{ $labels.instance }})
          description: "A container is absent for 5 min\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerHighCpuUtilization
        expr: '(sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod, container) / sum(container_spec_cpu_quota{container!=""}/container_spec_cpu_period{container!=""}) by (pod, container) * 100) > 80'
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Container High CPU utilization (instance {{ $labels.instance }})
          description: "Container CPU utilization is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerHighMemoryUsage
        expr: '(sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80'
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Container High Memory usage (instance {{ $labels.instance }})
          description: "Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerVolumeUsage
        expr: '(1 - (sum(container_fs_inodes_free{name!=""}) BY (instance) / sum(container_fs_inodes_total) BY (instance))) * 100 > 80'
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Container Volume usage (instance {{ $labels.instance }})
          description: "Container Volume usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerHighThrottleRate
        expr: 'sum(increase(container_cpu_cfs_throttled_periods_total{container!=""}[5m])) by (container, pod, namespace) / sum(increase(container_cpu_cfs_periods_total[5m])) by (container, pod, namespace) > ( 25 / 100 )'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Container high throttle rate (instance {{ $labels.instance }})
          description: "Container is being throttled\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerHighLowChangeCpuUsage
        expr: '(abs((sum by (instance, name) (rate(container_cpu_usage_seconds_total{name!=""}[1m])) * 100) - (sum by (instance, name) (rate(container_cpu_usage_seconds_total{name!=""}[1m] offset 1m)) * 100)) or abs((sum by (instance, name) (rate(container_cpu_usage_seconds_total{name!=""}[1m])) * 100) - (sum by (instance, name) (rate(container_cpu_usage_seconds_total{name!=""}[5m] offset 1m)) * 100))) > 25'
        for: 0m
        labels:
          severity: info
        annotations:
          summary: Container high low change CPU usage (instance {{ $labels.instance }})
          description: "This alert rule monitors the absolute change in CPU usage within a time window and triggers an alert when the change exceeds 25%.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerLowCpuUtilization
        expr: '(sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod, container) / sum(container_spec_cpu_quota{container!=""}/container_spec_cpu_period{container!=""}) by (pod, container) * 100) < 20'
        for: 7d
        labels:
          severity: info
        annotations:
          summary: Container Low CPU utilization (instance {{ $labels.instance }})
          description: "Container CPU utilization is under 20% for 1 week. Consider reducing the allocated CPU.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerLowMemoryUsage
        expr: '(sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) < 20'
        for: 7d
        labels:
          severity: info
        annotations:
          summary: Container Low Memory usage (instance {{ $labels.instance }})
          description: "Container Memory usage is under 20% for 1 week. Consider reducing the allocated memory.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ContainerMemoryUsageHigh
        annotations:
          summary: 'Container {{ $labels.name }} memory usage is high'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its allocated memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: (container_memory_usage_bytes{container_label_com_docker_compose_config_hash=~".+", container_label_stackname="docker-monitoring-stack-gpnc"} / container_spec_memory_limit_bytes) > 0.8
        for: 5m
        labels:
          severity: warning

      - alert: ContainerMemoryAlmostOut
        annotations:
          summary: 'Container {{ $labels.name }} memory almost full'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 90% of its allocated memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: (container_memory_usage_bytes{container_label_com_docker_compose_config_hash=~".+", container_label_stackname="docker-monitoring-stack-gpnc"} / container_spec_memory_limit_bytes) > 0.9
        for: 2m
        labels:
          severity: critical

      - alert: ContainerCPUThrottlingHigh
        annotations:
          summary: 'Container {{ $labels.name }} experiencing high CPU throttling'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is experiencing high CPU throttling.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: rate(container_cpu_cfs_throttled_periods_total[5m]) / rate(container_cpu_cfs_periods_total[5m]) > 0.2
        for: 5m
        labels:
          severity: warning

      - alert: ContainerCPUUsageHigh
        annotations:
          summary: 'Container {{ $labels.name }} CPU usage is high'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its allocated CPU.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: rate(container_cpu_usage_seconds_total[1m]) > (container_spec_cpu_quota / container_spec_cpu_period * 0.8)
        for: 5m
        labels:
          severity: warning

      - alert: ContainerDiskUsageHigh
        annotations:
          summary: 'Container {{ $labels.name }} disk usage is high'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its disk quota.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: container_fs_usage_bytes / container_fs_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning

      - alert: ContainerDiskAlmostOut
        annotations:
          summary: 'Container {{ $labels.name }} almost out of disk space'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 90% of its disk quota.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: container_fs_usage_bytes / container_fs_limit_bytes > 0.9
        for: 5m
        labels:
          severity: critical

      - alert: ContainerRestarts
        annotations:
          summary: 'Container {{ $labels.name }} restarted'
          description: "The container {{ $labels.name }} on instance {{ $labels.instance }} has restarted more than 3 times in the last 5 minutes.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
        expr: rate(container_restart_count_total[5m]) > 3
        for: 5m
        labels:
          severity: critical
